language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_90758773777b_key -iv $encrypted_90758773777b_iv
  -in deploy.key.enc -out ./.travis/deploy.key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan marcusnoble.co.uk >> ~/.ssh/known_hosts
- git remote add dokku dokku@marcusnoble.co.uk:dobot
- git config --global push.default simple
script:
- git push dokku master
branches:
  only:
  - master
